### ISSUE TITLE
Unexpected behavior with `IOR` / `IOW`

### ISSUE THREAD

**Issue by AndrewFasano** [rehosting/hyperfs#15]
Based a symex test created by @jamcleod, I tried getting a better understanding of what's going on with `IOR` and `IOW` ioctls (related to #7). The results of the config below are not what I'd expect.

## Observed behavior
With explicit IOCTL models, both read and write IOCTLs return what's specified in the model (return 0) but fail to trigger the read/write methods for our modeled pseudofile. Without the models, the IOCTLs fail entirely.

```
open("/dev/missing", O_RDWR|O_LARGEFILE) = 3
ioctl(3, _IOC(_IOC_WRITE, 0x45, 0x2, 0x1000), 0xbeffd508) = 0
write(1, "Ioctl return value is ", 22Ioctl return value is )  = 22
write(1, "i", 1i)                        = 1
write(1, "\n", 1
)                       = 1
ioctl(3, _IOC(_IOC_READ, 0x45, 0x2, 0x1000), 0xbeffe508) = 0
write(1, "Ioctl return value is ", 22Ioctl return value is )  = 22
write(1, "i", 1i)                        = 1
write(1, " with value ", 12 with value )            = 12
```

### Just read from device
Comment out the block of code starting with `// WRITE TO DEVICE`, leave the `// READ TO DEVICE` block uncommented

The IOCTL model for 0x90004502 seems to control if we get -ENOTTY or not. If we leave the model as shown below we get:
```
ioctl(3, _IOC(_IOC_READ, 0x45, 0x2, 0x1000), 0xbeffe508) = 0
write(1, "Ioctl return value is ", 22Ioctl return value is )  = 22
write(1, "i", 1i)                        = 1
write(1, " with value ", 12 with value )            = 12
```

But we comment out the IOCTL model, we get an `-ENOTTY` error:
```
open("/dev/missing", O_RDWR|O_LARGEFILE) = 3
ioctl(3, _IOC(_IOC_READ, 0x45, 0x2, 0x1000), 0xbeffe510) = -1 ENOTTY (Not a tty)
write(1, "Ioctl return value is ", 22Ioctl return value is )  = 22
write(1, "i", 1i)                        = 1
write(1, " with value ", 12 with value )            = 12
```

-----

To set this up, place this file in penguin's `tests/unit_tests/config/ioctl.yaml`, add a check in tests/unit_tests/test.py:
```
        "ioctl": assert_generic("console.log", "tests pass"),
```
and add `ioctl` to .github/build.yaml under the list of tests in `run_tests`.

```yaml
core:
  root_shell: false
  strace: true

env:
  igloo_init: /init

pseudofiles:
  /dev/missing:
    size: 12
    read:
      model: const_buf
      val: Hello world
    write:
      model: default
    ioctl:
      # _IOC_WRITE
      0x50004502:
        model: return_const
        val: 0
      # _IOC_READ
      0x90004502:
        model: return_const
        val: 0

lib_inject:
  extra: |
    #include <fcntl.h>
    #include <sys/ioctl.h>
    #include <stdio.h>

    #define CMD_TYPE 0x45
    #define READ_CMD _IOR(CMD_TYPE, 2, char[4096]) // read *FROM* device into user buffer
    #define WRITE_CMD _IOW(CMD_TYPE, 2, char[4096]) // write *TO* device from user buffer
    
    void check_dev_missing() {
        char buffer[4096] = {0};
        int fd = open("/dev/missing", O_RDWR);
        if(fd == -1) {
            printf("/dev/missing could not be opened!\n");
            return;
        }

        // WRITE TO DEVICE
        char buffer2[4096] = "Userspace message";
        int ret = ioctl(fd, WRITE_CMD, buffer2);
        printf("Ioctl return value is %i\n", ret);

        // READ FROM DEVICE
        ret = ioctl(fd, READ_CMD, buffer);
        printf("Ioctl return value is %i with value %s\n", ret, buffer);

        //printf("tests pass\n");
    }
static_files:
  /init:
    type: inline_file
    mode: 73
    contents: |
      #!/igloo/utils/micropython
      import ffi
      lib_inject = ffi.open("lib_inject.so")
      check_dev_missing = lib_inject.func("v", "check_dev_missing", "")
      check_dev_missing()
```

Then run with:
```
python3 test.py --arch armel --test ioctl
```
