### ISSUE TITLE
-ENOTCONN after large seek

### ISSUE THREAD

**Issue by AndrewFasano** [rehosting/hyperfs#24]
After a large seek hyperfs seems to die or end up in a weird state where it no longer functions. Userspace sees `-ENOTCONN` when it tries interacting with hyperfs-modeled files after this occurs.

Reproduce with the following penguin unit tests (i.e., create it at penguin/tests/unit_tests/test_target/patches/tests/pseudofile_seek.yaml, then edit penguin/tests/unit_tests/base_config.yaml to include it as a patch). I've been testing with `armel`.

```yaml
plugins:
  verifier:
    conditions:
      pseudofile_seek+console:
        type: file_contains
        file: console.log
        string: "/tests/pseudofile_seek.sh PASS"

pseudofiles:
  /dev/present:
    ioctl:
      '*':
        model: return_const
        val: 0
    read:
      model: zero
    write:
      model: discard

static_files:
  /tests/pseudofile_seek.sh:
    type: inline_file
    contents: |
      #!/igloo/utils/micropython
      import os

      # Path to the device file
      device_path = "/dev/present"
      failed = False

      try:
        # Open the device with read and write permissions
          fd = open(device_path, 'r+b')  # 'r+b' mode allows both reading and writing in binary mode
      except OSError as e:
          print(f"Failed to open device: {e}")
          raise SystemExit(1)

      try:
          # Seek to the specified offset (large value)
          offset = 2**16-1
          fd.seek(offset)

          # Data to write (4 zero bytes)
          buffer = bytes([0, 0, 0, 0])

          # Write 4 bytes to the device
          bytes_written = fd.write(buffer)
          if bytes_written < len(buffer):
            print("Incomplete write occurred.")

          print(f"Successfully wrote {bytes_written} bytes to the device.")
      except OSError as e:
          print(f"Write failed: {e}")
          failed = True
          #raise SystemExit(1)
      finally:
          # Close the device
          fd.close()

      try:
        with open("/proc/self/cmdline", "rb") as f:
          print("Proc self cmdline:", f.read())
      except Exception as e:
        print(f"Proc access failed: {e}")
        failed = True

      if failed:
        raise SystemExit(1)

    mode: 73
```

This produces output (in `results/latest/shared/tests/pseudofile_seek.sh/stdout`) showing:
```
Write failed: [Errno 103] ECONNABORTED
Proc access failed: [Errno 107] ENOTCONN
```
